version: "3"
services:
  app:
    build: .
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - REACT_APP_IPTV_PROVIDER=${REACT_APP_IPTV_PROVIDER}
      - EPG_URL=${EPG_URL}
      - EPG_USERNAME=${EPG_USERNAME}
      - EPG_PASSWORD=${EPG_PASSWORD}
  db:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
