version: "3"
services:
  app:
    build: .
    ports:
      - "80:${APP_PORT}"
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
  db:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
